// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiRZnE_qIjsznT_MJyX8uO_a7XIqOgews',
    appId: '1:514569505112:web:d5b363f94b9e57c0233d2d',
    messagingSenderId: '514569505112',
    projectId: 'myplanner-e3906',
    authDomain: 'myplanner-e3906.firebaseapp.com',
    storageBucket: 'myplanner-e3906.appspot.com',
    measurementId: 'G-V0VSGCB4CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTPwEv6_AtvAfyG0uYabdKfZsjcrN8Y94',
    appId: '1:514569505112:android:c383ecef01846b91233d2d',
    messagingSenderId: '514569505112',
    projectId: 'myplanner-e3906',
    storageBucket: 'myplanner-e3906.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCERHa6f80bQJrfb9f7wAz1SoCdrhXngK8',
    appId: '1:514569505112:ios:b64c581a7cbe2f18233d2d',
    messagingSenderId: '514569505112',
    projectId: 'myplanner-e3906',
    storageBucket: 'myplanner-e3906.appspot.com',
    iosBundleId: 'com.example.novapasta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCERHa6f80bQJrfb9f7wAz1SoCdrhXngK8',
    appId: '1:514569505112:ios:29ebcd1d9b954cfa233d2d',
    messagingSenderId: '514569505112',
    projectId: 'myplanner-e3906',
    storageBucket: 'myplanner-e3906.appspot.com',
    iosBundleId: 'com.example.novapasta.RunnerTests',
  );
}
